language: java

cache:
    directories:
        - "$HOME/.m2"

script: mvn verify -P execute-documentation

after_success:
    - bash <(curl -s https://codecov.io/bash)

after_failure:
    - cat /home/travis/build/fridujo/retrokompat/maven-plugin/target/git/fridujo/classpath-junit-extension/log.txt
    - cat /home/travis/build/fridujo/retrokompat/maven-plugin/target/git/apache/maven-dependency-analyzer/log.txt
