name: Build

on: push

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v2
              with:
                  distribution: 'temurin'
                  java-version: '8'
            - uses: actions/cache@v2
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-maven-
            - run: |
                  java -version
                  echo $JAVA_HOME
            - run: ./mvnw test
            - uses: codecov/codecov-action@v2
            - run: |
                  cat /home/travis/build/fridujo/retrokompat/maven-plugin/target/git/fridujo/classpath-junit-extension/log.txt
                  cat /home/travis/build/fridujo/retrokompat/maven-plugin/target/git/apache/maven-dependency-analyzer/log.txt
              if: ${{ failure() }}
